version: 2
updates:
  - package-ecosystem: 'github-actions' # This is to monitor GitHub Actions
    directory: '/' # Root directory where your workflows are located
    schedule:
      interval: 'weekly' # Perform checks weekly
